[package]
name = "janitor-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "janitor_rs"
crate-type = ["cdylib"]

[dependencies]
numpy = "0.27"

[dependencies.pyo3]
version = "0.27.0"